-- Medical Device Streaming: Deploy Streamlit Dashboard
-- Run this AFTER setup.sql has completed successfully.
-- Prerequisites: streamlit_app.py and environment.yml must already be uploaded
-- to @SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL.STREAMLIT_STAGE via PUT command.

USE ROLE ACCOUNTADMIN;
USE DATABASE SF_SOLUTIONS;
USE WAREHOUSE SF_SOLUTIONS_WH;
USE SCHEMA MEDICAL_DEVICE_CLINICAL;

CREATE STAGE IF NOT EXISTS SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL.STREAMLIT_STAGE
    DIRECTORY = (ENABLE = TRUE);

-- Create Streamlit app
CREATE OR REPLACE STREAMLIT SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL.MEDICAL_DEVICE_MONITOR
    FROM '@SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL.STREAMLIT_STAGE'
    MAIN_FILE = 'streamlit_app.py'
    QUERY_WAREHOUSE = SF_SOLUTIONS_WH;

ALTER STREAMLIT SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL.MEDICAL_DEVICE_MONITOR ADD LIVE VERSION FROM LAST;

-- Show Streamlit URL
SELECT
    'Medical Device Monitor deployed!' AS STATUS,
    'https://app.snowflake.com/' || LOWER(CURRENT_ORGANIZATION_NAME()) || '/' || LOWER(CURRENT_ACCOUNT_NAME())
        || '/#/streamlit-apps/SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL.MEDICAL_DEVICE_MONITOR' AS STREAMLIT_URL;
