-- =============================================================================
-- Solution: Medical Device Streaming Platform
-- Industry: Healthcare & Life Sciences
-- Database: SF_SOLUTIONS
-- Schemas:  MEDICAL_DEVICE_CLINICAL, MEDICAL_DEVICE_TELEMETRY
--
-- Real-time medical device data streaming platform demonstrating Snowflake's
-- High-Performance Snowpipe Streaming architecture for ECG, EDA, and PPG
-- biosignal data with live analytics via flattened views and ASOF joins.
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- Shared infrastructure (idempotent)
CREATE DATABASE IF NOT EXISTS SF_SOLUTIONS;
CREATE WAREHOUSE IF NOT EXISTS SF_SOLUTIONS_WH
    WITH WAREHOUSE_SIZE = 'LARGE'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE;

USE DATABASE SF_SOLUTIONS;
USE WAREHOUSE SF_SOLUTIONS_WH;

-- =============================================================================
-- SCHEMA: MEDICAL_DEVICE_CLINICAL
-- Clinical biosignal data from ECG, EDA, and PPG medical devices
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS MEDICAL_DEVICE_CLINICAL;
USE SCHEMA SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL;

-- Patient session management
CREATE TABLE IF NOT EXISTS PATIENT_SESSIONS (
    SESSION_ID VARCHAR(100) PRIMARY KEY,
    PATIENT_ID VARCHAR(50) NOT NULL,
    FACILITY_ID VARCHAR(50),
    ROOM_ID VARCHAR(50),
    SESSION_START_TIME TIMESTAMP_NTZ NOT NULL,
    SESSION_END_TIME TIMESTAMP_NTZ,
    SESSION_STATUS VARCHAR(20),
    SESSION_TYPE VARCHAR(50),
    ATTENDING_PHYSICIAN VARCHAR(100),
    PRIMARY_CONDITION VARCHAR(100),
    CLINICAL_PRIORITY VARCHAR(20),
    ACTIVE_DEVICES ARRAY,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Device inventory and assignment tracking
CREATE TABLE IF NOT EXISTS DEVICE_REGISTRY (
    DEVICE_ID VARCHAR(50) PRIMARY KEY,
    DEVICE_TYPE VARCHAR(20) NOT NULL,
    DEVICE_MODEL VARCHAR(50),
    FIRMWARE_VERSION VARCHAR(20),
    FACILITY_ID VARCHAR(50),
    ROOM_ID VARCHAR(50),
    CURRENT_PATIENT_ID VARCHAR(50),
    CURRENT_SESSION_ID VARCHAR(100),
    ASSIGNMENT_TIMESTAMP TIMESTAMP_NTZ,
    SAMPLING_RATES ARRAY,
    SUPPORTED_FEATURES VARIANT,
    STATUS VARCHAR(20),
    LAST_MAINTENANCE_DATE DATE,
    NEXT_MAINTENANCE_DUE DATE,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ECG (Electrocardiography) raw data
CREATE TABLE IF NOT EXISTS ECG_DATA (
    DATA VARIANT NOT NULL,
    PATIENT_ID VARCHAR(50) NOT NULL,
    TIMESTAMP_VAL TIMESTAMP_NTZ NOT NULL,
    LOAD_UTC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    APP_INGESTION_TIMESTAMP TIMESTAMP_NTZ
);

-- EDA (Electrodermal Activity) raw data
CREATE TABLE IF NOT EXISTS EDA_DATA (
    DATA VARIANT NOT NULL,
    PATIENT_ID VARCHAR(50) NOT NULL,
    TIMESTAMP_VAL TIMESTAMP_NTZ NOT NULL,
    LOAD_UTC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    APP_INGESTION_TIMESTAMP TIMESTAMP_NTZ
);

-- PPG (Photoplethysmography) raw data
CREATE TABLE IF NOT EXISTS PPG_DATA (
    DATA VARIANT NOT NULL,
    PATIENT_ID VARCHAR(50) NOT NULL,
    TIMESTAMP_VAL TIMESTAMP_NTZ NOT NULL,
    LOAD_UTC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    APP_INGESTION_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- PIPES: High-Performance Snowpipe Streaming (Clinical)
-- =============================================================================

CREATE OR REPLACE PIPE ECG_STREAMING_PIPE
AS
COPY INTO ECG_DATA (DATA, PATIENT_ID, TIMESTAMP_VAL, APP_INGESTION_TIMESTAMP)
FROM (
    SELECT $1, $1:patient_id, $1:timestamp, $1:app_ingestion_timestamp::TIMESTAMP_NTZ
    FROM TABLE(DATA_SOURCE(TYPE => 'STREAMING'))
);

CREATE OR REPLACE PIPE EDA_STREAMING_PIPE
AS
COPY INTO EDA_DATA (DATA, PATIENT_ID, TIMESTAMP_VAL, APP_INGESTION_TIMESTAMP)
FROM (
    SELECT $1, $1:patient_id, $1:timestamp, $1:app_ingestion_timestamp::TIMESTAMP_NTZ
    FROM TABLE(DATA_SOURCE(TYPE => 'STREAMING'))
);

CREATE OR REPLACE PIPE PPG_STREAMING_PIPE
AS
COPY INTO PPG_DATA (DATA, PATIENT_ID, TIMESTAMP_VAL, APP_INGESTION_TIMESTAMP)
FROM (
    SELECT $1, $1:patient_id, $1:timestamp, $1:app_ingestion_timestamp::TIMESTAMP_NTZ
    FROM TABLE(DATA_SOURCE(TYPE => 'STREAMING'))
);

-- =============================================================================
-- VIEWS: Flattened Clinical Data
-- =============================================================================

CREATE OR REPLACE VIEW ECG_DATA_FLATTENED AS
SELECT
    PATIENT_ID,
    TIMESTAMP_VAL,
    DATA:heart_rate::NUMBER AS HEART_RATE,
    DATA:lead_I::FLOAT AS LEAD_I,
    DATA:lead_II::FLOAT AS LEAD_II,
    DATA:lead_III::FLOAT AS LEAD_III,
    DATA:lead_V1::FLOAT AS LEAD_V1,
    DATA:lead_V2::FLOAT AS LEAD_V2,
    DATA:lead_V3::FLOAT AS LEAD_V3,
    DATA:lead_V4::FLOAT AS LEAD_V4,
    DATA:lead_V5::FLOAT AS LEAD_V5,
    DATA:lead_V6::FLOAT AS LEAD_V6,
    DATA:rhythm_classification::STRING AS RHYTHM_CLASSIFICATION,
    DATA:signal_quality::FLOAT AS SIGNAL_QUALITY,
    DATA:qt_interval::NUMBER AS QT_INTERVAL,
    DATA:st_elevation::FLOAT AS ST_ELEVATION,
    DATA:artifacts_detected::BOOLEAN AS ARTIFACTS_DETECTED,
    DATA:device_id::STRING AS DEVICE_ID,
    DATA:session_id::STRING AS SESSION_ID
FROM ECG_DATA;

CREATE OR REPLACE VIEW EDA_DATA_FLATTENED AS
SELECT
    PATIENT_ID,
    TIMESTAMP_VAL,
    DATA:stress_indicator::FLOAT AS STRESS_LEVEL,
    DATA:arousal_level::FLOAT AS AROUSAL_LEVEL,
    DATA:skin_conductance_level::FLOAT AS SKIN_CONDUCTANCE_LEVEL,
    DATA:skin_conductance_response::FLOAT AS SKIN_CONDUCTANCE_RESPONSE,
    DATA:emotional_valence::STRING AS EMOTIONAL_VALENCE,
    DATA:signal_quality::FLOAT AS SIGNAL_QUALITY,
    DATA:peak_amplitude::FLOAT AS PEAK_AMPLITUDE,
    DATA:rise_time_ms::NUMBER AS RISE_TIME_MS,
    DATA:half_recovery_time_ms::NUMBER AS HALF_RECOVERY_TIME_MS,
    DATA:scr_peaks_detected::NUMBER AS SCR_PEAKS_DETECTED,
    DATA:temperature_compensation::BOOLEAN AS TEMPERATURE_COMPENSATION,
    DATA:device_id::STRING AS DEVICE_ID,
    DATA:session_id::STRING AS SESSION_ID
FROM EDA_DATA;

CREATE OR REPLACE VIEW PPG_DATA_FLATTENED AS
SELECT
    PATIENT_ID,
    TIMESTAMP_VAL,
    DATA:spo2::FLOAT AS SPO2,
    DATA:heart_rate::NUMBER AS HEART_RATE,
    DATA:blood_pressure_estimate.systolic::NUMBER AS SYSTOLIC_BP,
    DATA:blood_pressure_estimate.diastolic::NUMBER AS DIASTOLIC_BP,
    DATA:pulse_wave_velocity::FLOAT AS PULSE_WAVE_VELOCITY,
    DATA:arterial_stiffness::FLOAT AS ARTERIAL_STIFFNESS,
    DATA:perfusion_index::FLOAT AS PERFUSION_INDEX,
    DATA:signal_quality::FLOAT AS SIGNAL_QUALITY,
    DATA:raw_ppg_signal::FLOAT AS RAW_PPG_SIGNAL,
    DATA:systolic_peak::FLOAT AS SYSTOLIC_PEAK,
    DATA:diastolic_notch::FLOAT AS DIASTOLIC_NOTCH,
    DATA:motion_artifacts::BOOLEAN AS MOTION_ARTIFACTS,
    DATA:device_id::STRING AS DEVICE_ID,
    DATA:session_id::STRING AS SESSION_ID
FROM PPG_DATA;

-- =============================================================================
-- VIEW: Consolidated Patient Vital Signs (ASOF Joins)
-- Real-time 5-minute window combining ECG, EDA, and PPG measurements
-- =============================================================================

CREATE OR REPLACE VIEW PATIENT_VITAL_SIGNS AS
WITH patient_list AS (
    SELECT DISTINCT PATIENT_ID
    FROM (
        SELECT PATIENT_ID FROM ECG_DATA_FLATTENED
        UNION ALL
        SELECT PATIENT_ID FROM EDA_DATA_FLATTENED
        UNION ALL
        SELECT PATIENT_ID FROM PPG_DATA_FLATTENED
    )
    WHERE PATIENT_ID IS NOT NULL
),
time_sequence AS (
    SELECT
        DATEADD(
            'SECOND',
            -ROW_NUMBER() OVER (ORDER BY SEQ4()) + 1,
            CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ
        ) AS TIMESTAMP_SEC
    FROM TABLE(GENERATOR(ROWCOUNT => 300))
),
time_spine AS (
    SELECT
        p.PATIENT_ID,
        t.TIMESTAMP_SEC
    FROM patient_list AS p
    CROSS JOIN time_sequence AS t
)
SELECT
    spine.PATIENT_ID,
    spine.TIMESTAMP_SEC,

    -- ECG vital signs
    COALESCE(ecg_exact.HEART_RATE, ecg_prop.HEART_RATE) AS ECG_HEART_RATE,
    COALESCE(ecg_exact.RHYTHM_CLASSIFICATION, ecg_prop.RHYTHM_CLASSIFICATION) AS RHYTHM_CLASSIFICATION,
    COALESCE(ecg_exact.QT_INTERVAL, ecg_prop.QT_INTERVAL) AS QT_INTERVAL,
    COALESCE(ecg_exact.ST_ELEVATION, ecg_prop.ST_ELEVATION) AS ST_ELEVATION,
    COALESCE(ecg_exact.SIGNAL_QUALITY, ecg_prop.SIGNAL_QUALITY) AS ECG_SIGNAL_QUALITY,
    COALESCE(ecg_exact.ARTIFACTS_DETECTED, ecg_prop.ARTIFACTS_DETECTED) AS ECG_ARTIFACTS,
    COALESCE(ecg_exact.DEVICE_ID, ecg_prop.DEVICE_ID) AS ECG_DEVICE_ID,
    COALESCE(ecg_exact.SESSION_ID, ecg_prop.SESSION_ID) AS ECG_SESSION_ID,

    -- EDA vital signs
    COALESCE(eda_exact.STRESS_LEVEL, eda_prop.STRESS_LEVEL) AS STRESS_LEVEL,
    COALESCE(eda_exact.AROUSAL_LEVEL, eda_prop.AROUSAL_LEVEL) AS AROUSAL_LEVEL,
    COALESCE(eda_exact.SKIN_CONDUCTANCE_LEVEL, eda_prop.SKIN_CONDUCTANCE_LEVEL) AS SKIN_CONDUCTANCE_LEVEL,
    COALESCE(eda_exact.SKIN_CONDUCTANCE_RESPONSE, eda_prop.SKIN_CONDUCTANCE_RESPONSE) AS SKIN_CONDUCTANCE_RESPONSE,
    COALESCE(eda_exact.EMOTIONAL_VALENCE, eda_prop.EMOTIONAL_VALENCE) AS EMOTIONAL_VALENCE,
    COALESCE(eda_exact.SIGNAL_QUALITY, eda_prop.SIGNAL_QUALITY) AS EDA_SIGNAL_QUALITY,
    COALESCE(eda_exact.DEVICE_ID, eda_prop.DEVICE_ID) AS EDA_DEVICE_ID,
    COALESCE(eda_exact.SESSION_ID, eda_prop.SESSION_ID) AS EDA_SESSION_ID,

    -- PPG vital signs
    COALESCE(ppg_exact.SPO2, ppg_prop.SPO2) AS SPO2,
    COALESCE(ppg_exact.HEART_RATE, ppg_prop.HEART_RATE) AS PPG_HEART_RATE,
    COALESCE(ppg_exact.SYSTOLIC_BP, ppg_prop.SYSTOLIC_BP) AS SYSTOLIC_BP,
    COALESCE(ppg_exact.DIASTOLIC_BP, ppg_prop.DIASTOLIC_BP) AS DIASTOLIC_BP,
    COALESCE(ppg_exact.PULSE_WAVE_VELOCITY, ppg_prop.PULSE_WAVE_VELOCITY) AS PULSE_WAVE_VELOCITY,
    COALESCE(ppg_exact.ARTERIAL_STIFFNESS, ppg_prop.ARTERIAL_STIFFNESS) AS ARTERIAL_STIFFNESS,
    COALESCE(ppg_exact.PERFUSION_INDEX, ppg_prop.PERFUSION_INDEX) AS PERFUSION_INDEX,
    COALESCE(ppg_exact.SIGNAL_QUALITY, ppg_prop.SIGNAL_QUALITY) AS PPG_SIGNAL_QUALITY,
    COALESCE(ppg_exact.MOTION_ARTIFACTS, ppg_prop.MOTION_ARTIFACTS) AS PPG_MOTION_ARTIFACTS,
    COALESCE(ppg_exact.DEVICE_ID, ppg_prop.DEVICE_ID) AS PPG_DEVICE_ID,
    COALESCE(ppg_exact.SESSION_ID, ppg_prop.SESSION_ID) AS PPG_SESSION_ID,

    -- Source timestamps
    COALESCE(ecg_exact.TIMESTAMP_VAL, ecg_prop.TIMESTAMP_VAL) AS ECG_SOURCE_TIMESTAMP,
    COALESCE(eda_exact.TIMESTAMP_VAL, eda_prop.TIMESTAMP_VAL) AS EDA_SOURCE_TIMESTAMP,
    COALESCE(ppg_exact.TIMESTAMP_VAL, ppg_prop.TIMESTAMP_VAL) AS PPG_SOURCE_TIMESTAMP,

    -- Data freshness (seconds since actual reading)
    CASE
        WHEN ecg_exact.TIMESTAMP_VAL IS NOT NULL THEN 0
        WHEN ecg_prop.TIMESTAMP_VAL IS NOT NULL THEN
            TIMESTAMPDIFF('SECOND', ecg_prop.TIMESTAMP_VAL, spine.TIMESTAMP_SEC)
        ELSE NULL
    END AS ECG_AGE_SECONDS,
    CASE
        WHEN eda_exact.TIMESTAMP_VAL IS NOT NULL THEN 0
        WHEN eda_prop.TIMESTAMP_VAL IS NOT NULL THEN
            TIMESTAMPDIFF('SECOND', eda_prop.TIMESTAMP_VAL, spine.TIMESTAMP_SEC)
        ELSE NULL
    END AS EDA_AGE_SECONDS,
    CASE
        WHEN ppg_exact.TIMESTAMP_VAL IS NOT NULL THEN 0
        WHEN ppg_prop.TIMESTAMP_VAL IS NOT NULL THEN
            TIMESTAMPDIFF('SECOND', ppg_prop.TIMESTAMP_VAL, spine.TIMESTAMP_SEC)
        ELSE NULL
    END AS PPG_AGE_SECONDS

FROM time_spine AS spine

-- Exact match joins
LEFT JOIN ECG_DATA_FLATTENED AS ecg_exact
    ON spine.PATIENT_ID = ecg_exact.PATIENT_ID
    AND spine.TIMESTAMP_SEC = ecg_exact.TIMESTAMP_VAL

LEFT JOIN EDA_DATA_FLATTENED AS eda_exact
    ON spine.PATIENT_ID = eda_exact.PATIENT_ID
    AND spine.TIMESTAMP_SEC = eda_exact.TIMESTAMP_VAL

LEFT JOIN PPG_DATA_FLATTENED AS ppg_exact
    ON spine.PATIENT_ID = ppg_exact.PATIENT_ID
    AND spine.TIMESTAMP_SEC = ppg_exact.TIMESTAMP_VAL

-- ASOF joins for forward-fill propagation
ASOF JOIN ECG_DATA_FLATTENED AS ecg_prop
    MATCH_CONDITION(spine.TIMESTAMP_SEC >= ecg_prop.TIMESTAMP_VAL)
    ON spine.PATIENT_ID = ecg_prop.PATIENT_ID

ASOF JOIN EDA_DATA_FLATTENED AS eda_prop
    MATCH_CONDITION(spine.TIMESTAMP_SEC >= eda_prop.TIMESTAMP_VAL)
    ON spine.PATIENT_ID = eda_prop.PATIENT_ID

ASOF JOIN PPG_DATA_FLATTENED AS ppg_prop
    MATCH_CONDITION(spine.TIMESTAMP_SEC >= ppg_prop.TIMESTAMP_VAL)
    ON spine.PATIENT_ID = ppg_prop.PATIENT_ID

ORDER BY spine.PATIENT_ID, spine.TIMESTAMP_SEC;

-- =============================================================================
-- SCHEMA: MEDICAL_DEVICE_TELEMETRY
-- Device health, connectivity, and operational telemetry
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS MEDICAL_DEVICE_TELEMETRY;
USE SCHEMA SF_SOLUTIONS.MEDICAL_DEVICE_TELEMETRY;

-- Device telemetry raw data
CREATE TABLE IF NOT EXISTS DEVICE_TELEMETRY (
    DATA VARIANT NOT NULL,
    TIMESTAMP_VAL TIMESTAMP_NTZ NOT NULL,
    LOAD_UTC_TIMESTAMP TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ,
    APP_INGESTION_TIMESTAMP TIMESTAMP_NTZ
);

-- =============================================================================
-- PIPE: High-Performance Snowpipe Streaming (Telemetry)
-- =============================================================================

CREATE OR REPLACE PIPE TELEMETRY_STREAMING_PIPE
AS
COPY INTO DEVICE_TELEMETRY (DATA, TIMESTAMP_VAL, APP_INGESTION_TIMESTAMP)
FROM (
    SELECT $1, $1:timestamp, $1:app_ingestion_timestamp::TIMESTAMP_NTZ
    FROM TABLE(DATA_SOURCE(TYPE => 'STREAMING'))
);

-- =============================================================================
-- VIEW: Flattened Device Telemetry
-- =============================================================================

CREATE OR REPLACE VIEW DEVICE_TELEMETRY_FLATTENED AS
SELECT
    TIMESTAMP_VAL,
    DATA:device_id::STRING AS DEVICE_ID,
    DATA:device_type::STRING AS DEVICE_TYPE,
    DATA:battery_level::NUMBER AS BATTERY_LEVEL,
    DATA:signal_strength::NUMBER AS SIGNAL_STRENGTH,
    DATA:connection_status::STRING AS CONNECTION_STATUS,
    DATA:data_transmission_rate::FLOAT AS DATA_TRANSMISSION_RATE,
    DATA:successful_transmissions::NUMBER AS SUCCESSFUL_TRANSMISSIONS,
    DATA:failed_transmissions::NUMBER AS FAILED_TRANSMISSIONS,
    DATA:packet_loss_rate::FLOAT AS PACKET_LOSS_RATE,
    DATA:latency_ms::NUMBER AS LATENCY_MS,
    DATA:cpu_usage::FLOAT AS CPU_USAGE,
    DATA:memory_usage::FLOAT AS MEMORY_USAGE,
    DATA:storage_usage::FLOAT AS STORAGE_USAGE,
    DATA:temperature::FLOAT AS TEMPERATURE,
    DATA:uptime_hours::FLOAT AS UPTIME_HOURS,
    DATA:maintenance_status::STRING AS MAINTENANCE_STATUS,
    DATA:calibration_status::STRING AS CALIBRATION_STATUS,
    DATA:firmware_version::STRING AS FIRMWARE_VERSION,
    DATA:facility_id::STRING AS FACILITY_ID,
    DATA:room_id::STRING AS ROOM_ID
FROM DEVICE_TELEMETRY;

-- =============================================================================
-- GRANTS: Allow streaming and query access
-- =============================================================================

-- Clinical schema grants
GRANT USAGE ON SCHEMA SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL TO ROLE PUBLIC;
GRANT SELECT ON ALL TABLES IN SCHEMA SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL TO ROLE PUBLIC;
GRANT SELECT ON ALL VIEWS IN SCHEMA SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL TO ROLE PUBLIC;
GRANT INSERT ON ALL TABLES IN SCHEMA SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL TO ROLE PUBLIC;

-- Clinical pipes grants
GRANT OPERATE ON PIPE SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL.ECG_STREAMING_PIPE TO ROLE PUBLIC;
GRANT MONITOR ON PIPE SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL.ECG_STREAMING_PIPE TO ROLE PUBLIC;
GRANT OPERATE ON PIPE SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL.EDA_STREAMING_PIPE TO ROLE PUBLIC;
GRANT MONITOR ON PIPE SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL.EDA_STREAMING_PIPE TO ROLE PUBLIC;
GRANT OPERATE ON PIPE SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL.PPG_STREAMING_PIPE TO ROLE PUBLIC;
GRANT MONITOR ON PIPE SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL.PPG_STREAMING_PIPE TO ROLE PUBLIC;

-- Telemetry schema grants
GRANT USAGE ON SCHEMA SF_SOLUTIONS.MEDICAL_DEVICE_TELEMETRY TO ROLE PUBLIC;
GRANT SELECT ON ALL TABLES IN SCHEMA SF_SOLUTIONS.MEDICAL_DEVICE_TELEMETRY TO ROLE PUBLIC;
GRANT SELECT ON ALL VIEWS IN SCHEMA SF_SOLUTIONS.MEDICAL_DEVICE_TELEMETRY TO ROLE PUBLIC;
GRANT INSERT ON ALL TABLES IN SCHEMA SF_SOLUTIONS.MEDICAL_DEVICE_TELEMETRY TO ROLE PUBLIC;

-- Telemetry pipe grants
GRANT OPERATE ON PIPE SF_SOLUTIONS.MEDICAL_DEVICE_TELEMETRY.TELEMETRY_STREAMING_PIPE TO ROLE PUBLIC;
GRANT MONITOR ON PIPE SF_SOLUTIONS.MEDICAL_DEVICE_TELEMETRY.TELEMETRY_STREAMING_PIPE TO ROLE PUBLIC;

-- =============================================================================
-- STREAMLIT: Medical Device Monitor Dashboard (SiS)
-- Stage is created here. Actual deployment (PUT + CREATE STREAMLIT + ADD LIVE VERSION)
-- is handled by deploy_streamlit.sql which is executed from the SKILL.md installer.
-- =============================================================================

USE SCHEMA SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL;

CREATE STAGE IF NOT EXISTS SF_SOLUTIONS.MEDICAL_DEVICE_CLINICAL.STREAMLIT_STAGE
    DIRECTORY = (ENABLE = TRUE);
